### ISSUE TITLE
What exactly is this package?

### ISSUE THREAD

**Issue by cansurmeli** [mapbox/mapbox-common-ios#28]
Hey.

I'll be blunt. I'm confused as to what this package represents.

How is this any different than the regular Mapbox iOS SDK? Sure, it has a different version number but the README fall sshy of explaining what exactly does this package provides. Is it just a separate implementation supporting SPM?

Any info would be appreciated?

Thanks.

**Comment by 1ec5** [comment]
The MapboxCommon package contains the cross-platform functionality shared between Mapbox’s map, navigation, and search SDKs, as well as automatically generated interfaces in platform-specific languages. This repository exists primarily so that SPM can easily discover the MapboxCommon binaries, which are hosted on mapbox.com.
